workspace/DevP360/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GenderLabel__c</fullName>
        <label>GenderLabel</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HealthCloudGA__SourceSystem__c</fullName>
        <defaultValue>&quot;Health1-&quot;+$Organization.Id</defaultValue>
        <description>Identifies the system that created the record and owns update rights to it.</description>
        <inlineHelpText>Identifies the system that created the record and owns update rights to it. Defaults to Health1 for manually created records.</inlineHelpText>
        <label>Source System</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Medicaid_CIN__c</fullName>
        <label>Medicaid CIN</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace/QASB1 Copy 8 25/src/classes/clinicalSummaryControllerTest.cls
/*
Description: 1. to test method fetching field name and their data type to show in list  
Created By : Cognizant Technology Solutions
Create Date: 02/02/2017
*/

@isTest
private class clinicalSummaryControllerTest {
    
   private static testMethod void fetchDynamicRecordTest() {
        clinicalSummaryController objcsc = new clinicalSummaryController();
       
        String strRecordTypeId = [Select Id From RecordType Where SobjectType = 'Account' and Name = 'Individual'].Id;

        Account ac = new Account(RecordTypeId = strRecordTypeId, Name='James33', First_Name__c='James33', Last_Name__c = 'Franklin33', GenderLabel__c = 'M', Date_of_Birth__c = Date.newInstance(1975,12,10), Medicaid_CIN__c = '468927');
        insert ac;
       
        String strQuery  =  'SELECT HealthCloudGA__Reaction255__c ,HealthCloudGA__StatusLabel__c,HealthCloudGA__CriticalityLabel__c, HealthCloudGA__SourceSystem__c, Source_System_MRN__c FROM HealthCloudGA__EhrAllergyIntolerance__c ';
        String whereQuery =  ' WHERE HealthCloudGA__Account__c = :patientId ';
        String patientId =  ac.id;
        String recordLimit = objcsc.rLimit;
        String[] lstFielddatatype =   new List<String>();
        lstFielddatatype.add('String');
        lstFielddatatype.add('String');
        lstFielddatatype.add('String');
        lstFielddatatype.add('String');
        lstFielddatatype.add('String');
       
        clinicalSummaryController.sObjectWrapper objsow;
        objsow = clinicalSummaryController.dynfetchRecords(strQuery, whereQuery,lstFielddatatype, patientId, recordLimit); 
      
        System.assertEquals('HealthCloudGA__Reaction255__c##String', objsow.lstFieldApi[0]);
        System.assertEquals('HealthCloudGA__StatusLabel__c##String', objsow.lstFieldApi[1]);
        System.assertEquals('HealthCloudGA__CriticalityLabel__c##String', objsow.lstFieldApi[2]);
        System.assertEquals('HealthCloudGA__SourceSystem__c##String', objsow.lstFieldApi[3]);
        System.assertEquals('Source_System_MRN__c##String', objsow.lstFieldApi[4]);
     
        clinicalSummaryController.sObjectWrapper objsow1;
        objsow1 = clinicalSummaryController.dynfetchRecords(strQuery, whereQuery,lstFielddatatype, patientId, '0'); 
       
        System.assertEquals('HealthCloudGA__Reaction255__c##String', objsow1.lstFieldApi[0]);
        System.assertEquals('HealthCloudGA__StatusLabel__c##String', objsow1.lstFieldApi[1]);
        System.assertEquals('HealthCloudGA__CriticalityLabel__c##String', objsow1.lstFieldApi[2]);
        System.assertEquals('HealthCloudGA__SourceSystem__c##String', objsow1.lstFieldApi[3]);
        System.assertEquals('Source_System_MRN__c##String', objsow1.lstFieldApi[4]);
                
    }
    
}