workspace/DevP360/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GenderLabel__c</fullName>
        <label>GenderLabel</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Medicaid_CIN__c</fullName>
        <label>Medicaid CIN</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace/DevP360/src/objects/EHR_Social_History__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>EHR Social Histories</relationshipLabel>
        <relationshipName>EHR_Social_Histories</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assessment_Date__c</fullName>
        <description>The Date the Substance Use was assessed.</description>
        <label>Assessment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Frequency_of_Use__c</fullName>
        <label>Frequency of Use</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Substance__c</fullName>
        <label>Substance</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>EHR Social History</label>
    <nameField>
        <label>EHR Social History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EHR Social Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace/DevP360 9 18/src/classes/EHRSocialSummaryControllerTest.cls
/**
	@Author      :	Cognizant Technology Solutions
	@name        :	EHRSocialSummaryControllerTest
	@CreateDate  :	24/02/2017 
	@Description :  Test Class to validate Social History Object data based on patientId
	@Version     :	1.0
*/
@isTest(SeeAllData=false) 
public class EHRSocialSummaryControllerTest {
    
	static testMethod void validategetfindByPatientId() {
    	String strRecordTypeId = [Select Id From RecordType Where SobjectType = 'Account' and Name = 'Individual'].Id;
        Account ac = new Account(RecordTypeId = strRecordTypeId, Name='James', First_Name__c='James', Last_Name__c = 'Franklin', GenderLabel__c = 'M', Date_of_Birth__c = Date.newInstance(1975,12,10), Medicaid_CIN__c = '468927');
        insert ac;
        
        EHR_Social_History__c objShst = new EHR_Social_History__c( Account__c=ac.Id ,Assessment_Date__c = '1985/12/10', Frequency_of_Use__c = 'Occasionaly', Substance__c = '', User__c = 'No');
        Insert objShst;
                
        List<EHR_Social_History__c> lstShst = EHRSocialSummaryController.findByPatientId(ac.Id);
        System.assertEquals(lstShst[0].Assessment_Date__c, '1985/12/10');
        System.assertEquals(lstShst[0].Frequency_of_Use__c, 'Occasionaly');
        System.assertEquals(lstShst[0].Substance__c, null);
        System.assertEquals(lstShst[0].User__c, 'No');
    }

}