workspace/DevP360/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GenderLabel__c</fullName>
        <label>GenderLabel</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HealthCloudGA__SourceSystem__c</fullName>
        <defaultValue>&quot;Health1-&quot;+$Organization.Id</defaultValue>
        <description>Identifies the system that created the record and owns update rights to it.</description>
        <inlineHelpText>Identifies the system that created the record and owns update rights to it. Defaults to Health1 for manually created records.</inlineHelpText>
        <label>Source System</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Medicaid_CIN__c</fullName>
        <label>Medicaid CIN</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace/DevP360/src/classes/clinicalSummaryControllerTest.cls
@isTest
private class clinicalSummaryControllerTest {
	
   private static testMethod void fetchDynamicRecordTest() {
       
        clinicalSummaryController objcsc = new clinicalSummaryController();
        
        String strRecordTypeId = [Select Id From RecordType Where SobjectType = 'Account' and Name = 'Individual'].Id;

        Account ac = new Account(RecordTypeId = strRecordTypeId, Name='James33', First_Name__c='James33', Last_Name__c = 'Franklin33', GenderLabel__c = 'M', Date_of_Birth__c = Date.newInstance(1975,12,10), Medicaid_CIN__c = '468927');
        insert ac;
       
        String strQuery  =  'SELECT HealthCloudGA__Reaction255__c ,HealthCloudGA__StatusLabel__c,HealthCloudGA__CriticalityLabel__c, HealthCloudGA__SourceSystem__c, Source_System_MRN__c FROM HealthCloudGA__EhrAllergyIntolerance__c ';
        String whereQuery =  ' WHERE HealthCloudGA__Account__c = :patientId ';
        String patientId =  ac.id;
        String recordLimit = '3';
               

        clinicalSummaryController.sObjectWrapper objsow = clinicalSummaryController.dynfetchRecords(strQuery, whereQuery, patientId, recordLimit);  
        system.debug(objsow);
        
                
	}
    
}