workspace/DevP360/src/objects/Ehr_Clinical_Note__c.object
<CustomObject>
    <description>This object will hold many different categories of clinical notes:  Discharge Summaries, Advance Directives, Progress Notes, H&amp;P Notes, SOAP Notes, etc.</description>
    <fields>
        <fullName>Source_System_Id__c</fullName>
        <externalId>true</externalId>
        <label>Source System Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EHR Clinical Note</label>
    <nameField>
        <label>Ehr Clinical Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinical Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace/DevP360 9 18/src/classes/BehavioralHealthNotes.cls
global class BehavioralHealthNotes implements Database.Batchable<sObject>{

    global final String query = 'SELECT Ehr_Clinical_Note__c, Source_System_ID__c FROM Behavioral_Health_Note__c WHERE Ehr_Clinical_Note__c = null';
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Behavioral_Health_Note__c> bhNotes) {
        for(Behavioral_Health_Note__c s : bhNotes) {
            List<Ehr_Clinical_Note__c> theNote = [SELECT Id FROM Ehr_Clinical_Note__c WHERE Source_System_ID__c = :s.Source_System_ID__c];
            Id theNoteID = theNote[0].Id;
            s.Ehr_Clinical_Note__c = theNoteId;
        }
        update bhNotes;
    } 
    
    global void finish(Database.BatchableContext BC) {
        
    }

}