workspace/DevP360/src/objects/Ehr_Clinical_Note__c.object
<CustomObject>
    <description>This object will hold many different categories of clinical notes:  Discharge Summaries, Advance Directives, Progress Notes, H&amp;P Notes, SOAP Notes, etc.</description>
    <fields>
        <fullName>Note_Text__c</fullName>
        <label>Note Text</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>EHR Clinical Note</label>
    <nameField>
        <label>Ehr Clinical Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinical Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace/DevP360/src/objects/EHR_Procedure__c.object
<CustomObject>
    <description>This object holds procedural information</description>
    <fields>
        <fullName>Code_Label__c</fullName>
        <description>The human readable description of the procedure.</description>
        <label>Code Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EHR Procedure</label>
    <nameField>
        <displayFormat>EP-{0000}</displayFormat>
        <label>EHR Procedure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EHR Procedures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace/DevP360 9 18/src/classes/SearchApexClass.cls
// Author: Priyank Srivastava
// Patient 360 Search SOSL Query
// 

public class SearchApexClass {    
    
    @AuraEnabled
    public static List<List<SObject>> findAll(){
        return [FIND 'John' IN ALL FIELDS RETURNING Contact(ID,Name)];
    }    
	//System.debug(searchResult);

}
// Looks for word "John" in Contact Object
// How to connect this class to Component
// How to search in all the objects and return object names
// 
// // List<contact> obj = [Select ID, name from Contact Limit 5];
// System.debug(obj);

//List<List<SObject>> searchResult = [FIND 'John' IN ALL FIELDS RETURNING Contact(ID,Name)];
//System.debug(searchResult);

/*List<List<SObject>> searchList = [FIND 'CL-001' IN ALL FIELDS RETURNING Account (Id, Name), Contact, Opportunity, Lead,EHR_Procedure__c(Code_Label__c),	Ehr_Clinical_Note__c(Note_Text__c)];

for(List<Sobject> lst:searchList)
{
    System.debug(lst);
    
    //for(Sobject sobj:lst)
    //{
        //system.debug('RESULTS--'+sobj);
    //}
}

//system.debug('searchList--'+searchList);
//*/